-- require("shasherazi.plugins.mini.mini-files")
require("shasherazi.plugins.mini.mini-pairs")
-- require("shasherazi.plugins.mini.mini-starter")
require("shasherazi.plugins.mini.mini-tabline")
require("shasherazi.plugins.mini.mini-statusline")
require("shasherazi.plugins.mini.mini-move")
require("shasherazi.plugins.mini.mini-misc")
require("shasherazi.plugins.mini.mini-comment")
require("shasherazi.plugins.mini.mini-surround")
