require("shasherazi.core.options")
require("shasherazi.core.keymaps")
require("shasherazi.plugins")
require('shasherazi.plugins.dap.dap')
require("shasherazi.plugins.indent-blankline")
require("shasherazi.plugins.hardtime")
require("shasherazi.plugins.ufo")
-- require("shasherazi.plugins.neoscroll")
require("shasherazi.plugins.colorscheme")
-- require("shasherazi.plugins.fm-nvim")
require("shasherazi.plugins.nvim-tree")
require("shasherazi.plugins.fidget")
require("shasherazi.plugins.fterm")
require("shasherazi.plugins.nvim-tmux-navigation")
require('shasherazi.plugins.whichkey')
require('shasherazi.plugins.bufferline')
require('shasherazi.plugins.telescope')
-- require('shasherazi.plugins.feline')
require('shasherazi.plugins.lualine')
require('shasherazi.plugins.colorizer')
require('shasherazi.plugins.null-ls')
require('shasherazi.plugins.gitsigns')
require('shasherazi.plugins.autosave')
require('shasherazi.plugins.treesitter')
require('shasherazi.plugins.mini.init')
require('shasherazi.lsp.lspzero')
