require("shasherazi.options")
require("shasherazi.keymaps")
require("shasherazi.plugins")
require("shasherazi.colorscheme")
require("shasherazi.cmp")
require("shasherazi.lsp")
require("shasherazi.treesitter")
require("shasherazi.telescope")
require("shasherazi.autopairs")
require("shasherazi.comment")
require("shasherazi.gitsigns")
require("shasherazi.nvim-tree")
require("shasherazi.mini-files")
require("shasherazi.bufferline")
require("shasherazi.lualine")
require("shasherazi.toggleterm")
require("shasherazi.fterm")
require("shasherazi.impatient")
require("shasherazi.indentline")
require("shasherazi.tailwindcss-colors")
require("shasherazi.alpha")
-- require("shasherazi.ufo")
-- require("shasherazi.veil")
require('shasherazi.whichkey')
require("shasherazi.copilot")
require("shasherazi.colorizer")

