decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 0
    blur {
      enabled = yes
      size = 5
      ignore_opacity = true
      passes = 3
      new_optimizations = on
    }

    active_opacity = 0.85
    inactive_opacity = 0.85
    dim_inactive = true
    dim_strength = 0.2
}

windowrule = match:class .*, idleinhibit fullscreen

windowrule = match:class ^(Emulator)$, nodim
windowrule = match:title ^(Picture-in-Picture)$, nodim

windowrule = match:class ^(Alacritty)$, float
windowrule = match:class ^(kitty)$, float
windowrule = match:class ^(kitty)$, size 80% 80%
windowrule = match:title ^(.*fullscreen.*)$, fullscreen
windowrule = match:class ^(kitty)$, center

windowrule = match:class ^(firefox)$, opaque
windowrule = match:class ^(floorp)$, opaque
windowrule = match:class ^(waterfox)$, opaque
windowrule = match:class ^(LibreWolf)$, opaque
windowrule = match:class ^(Chromium)$, opaque
windowrule = match:class ^(blender)$, opaque
windowrule = match:class ^(brave-browser)$, opaque
windowrule = match:class ^(vivaldi-stable)$, opaque
windowrule = match:class ^(Gimp-2.10)$, opaque
windowrule = match:class ^(krita)$, opaque
windowrule = match:class ^(com.stremio.stremio)$, opaque
windowrule = match:class ^(Stremio)$, opaque
windowrule = match:class ^(mpv)$, opaque

windowrule = match:class ^(wofi)$, noborder
windowrule = match:class ^(dmenu)$, move 0 0

windowrule = match:class ^(firefox)$, workspace 3
windowrule = match:class ^(floorp)$, workspace 3
windowrule = match:class ^(waterfox)$, workspace 3
windowrule = match:class ^(LibreWolf)$, workspace 3
windowrule = match:class ^(Brave-browser)$, workspace 3
windowrule = match:class ^(vivaldi-stable)$, workspace 3
windowrule = match:class ^(Chromium)$, workspace 3
windowrule = match:class ^(Google-chrome)$, workspace 3

windowrule = match:class ^(Spotify)$, workspace 5

windowrule = match:class ^(discord)$, workspace 6
windowrule = match:class ^(vesktop)$, workspace 6
windowrule = match:class ^(WebCord)$, workspace 6
windowrule = match:class ^(Element)$, workspace 6

windowrule = match:class ^(Slack)$, workspace 7
windowrule = match:class ^(zoom)$, workspace 8
windowrule = match:class ^(thunderbird)$, workspace 9

windowrule = match:class ^(jetbrains-.*)$, match:title ^(win[0-9]+)$, float
windowrule = match:class ^(jetbrains-.*)$, match:title ^(win[0-9]+)$, nofocus

windowrule = match:class ^()$, match:title ^()$, noblur

layerrule = blur, rofi
layerrule = dimaround, rofi
