#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

nitrogen --set-zoom-fill --random
pkill picom
pkill polybar; polybar -l warning &
sh $HOME/dotfiles/mouseAndTouchpad.sh
sh $HOME/dotfiles/keyboard.sh
pkill dunst; dunst &
picom -b
/usr/bin/emacs --daemon &
if ! (ps aux | grep "thunderbird" | grep -v "grep"); then thunderbird& fi # start thunderbird if not already
clipmenud & # run clipmenu daemon

bspc monitor -d term files web code music discord slack zoom mail misc

bspc config border_width         1
bspc config focused_border_color "#00adb5"
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a Brave-browser desktop=web follow=on
bspc rule -a Nemo desktop=files follow=on
bspc rule -a Code desktop=code follow=on
bspc rule -a Spotify desktop=music follow=on
bspc rule -a discord desktop=discord follow=on
bspc rule -a thunderbird desktop=mail follow=on
bspc rule -a zoom desktop=zoom follow=on
bspc rule -a Slack desktop=slack follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled


bspc subscribe node_state | while read -r _ _ _ _ state flag; do
if [ "$state" != "fullscreen" ]; then
  continue
fi
if [ "$flag" == on ]; then
  $HOME/.local/bin/eww -c $HOME/.config/eww/bar close-all
else
  $HOME/.local/bin/eww -c $HOME/.config/eww/bar open bar
fi
done &
