#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

nitrogen --set-auto --random
killall picom; picom -b
killall polybar; polybar &
sh $HOME/dotfiles/mouseAndTouchpad.sh
sh $HOME/dotfiles/keyboard.sh
killall dunst; dunst &

bspc monitor -d term files web code music discord mail misc

bspc config border_width         1
bspc config focused_border_color "#fe8019"
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a Brave-browser desktop=web follow=on
bspc rule -a Thunar desktop=files follow=on
bspc rule -a Code desktop=code follow=on
bspc rule -a Spotify desktop=music follow=on
bspc rule -a discord desktop=discord follow=on
bspc rule -a Screenkey manage=off
