#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# some flatpak issue
systemctl --user import-environment DISPLAY XAUTHORITY
if command -v dbus-update-activation-environment >/dev/null 2>&1; then
   dbus-update-activation-environment DISPLAY XAUTHORITY
fi

nm-applet &
# sh ~/scripts/runIfNotAlreadyRunning.sh $(udiskie -t)&
nitrogen --set-zoom-fill --random
pkill picom
pkill polybar; polybar bspwm -l warning & disown
sh $HOME/dotfiles/scripts/inputDevicesConfig.sh
pkill dunst; dunst &
picom -b
if ! (ps aux | grep "thunderbird" | grep -v "grep"); then thunderbird& fi # start thunderbird if not already
export CM_SELECTIONS="clipboard" # monitor only "clipboard" clipboard for clipmenud
export $(dbus-launch)
clipmenud & # run clipmenu daemon
gammastep & # run gammastep

# bspc monitor -d term files web code music discord slack zoom mail misc
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config focused_border_color "#869aa4"
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a Alacritty state=floating
bspc rule -a Google-chrome desktop=3 follow=on
bspc rule -a Chromium desktop=3 follow=on
bspc rule -a Brave-browser desktop=3 follow=on
bspc rule -a Vivaldi-stable desktop=3 follow=on
bspc rule -a firefox desktop=3 follow=on
bspc rule -a Pcmanfm desktop=2 follow=on
bspc rule -a Thunar desktop=2 follow=on
bspc rule -a Code desktop=4 follow=on
bspc rule -a Spotify desktop=5 follow=on
bspc rule -a discord desktop=6 follow=on
bspc rule -a Element desktop=6 follow=on
bspc rule -a thunderbird desktop=9 follow=on
bspc rule -a zoom desktop=8 follow=on
bspc rule -a Slack desktop=7 follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

bspc subscribe node_state | while read -r _ _ _ _ state flag; do
  if [[ "$state" != fullscreen ]]; then continue; fi
  if [[ "$flag" == on ]]; then
    xdotool search --class eww-bar windowunmap
  else
    xdotool search --class eww-bar windowmap
  fi
done &
