#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

nm-applet &
nitrogen --restore
lxappearance &
pkill picom
pkill polybar; polybar bspwm -l warning & disown
sh $HOME/dotfiles/scripts/mouseAndTouchpad.sh
sh $HOME/dotfiles/scripts/keyboard.sh
pkill dunst; dunst &
killall lxappearance;
picom -b
if ! (ps aux | grep "thunderbird" | grep -v "grep"); then thunderbird& fi # start thunderbird if not already
export CM_SELECTIONS="clipboard" # monitor only "clipboard" clipboard for clipmenud
clipmenud & # run clipmenu daemon
keepassxc &

bspc monitor -d term files web code music discord slack zoom mail misc

bspc config border_width         1
bspc config focused_border_color "#869aa4"
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a Google-chrome desktop=web follow=on
bspc rule -a Chromium desktop=web follow=on
bspc rule -a firefox desktop=web follow=on
bspc rule -a Pcmanfm desktop=files follow=on
bspc rule -a Code desktop=code follow=on
bspc rule -a Spotify desktop=music follow=on
bspc rule -a discord desktop=discord follow=on
bspc rule -a thunderbird desktop=mail follow=on
bspc rule -a zoom desktop=zoom follow=on
bspc rule -a Slack desktop=slack follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

bspc subscribe node_state | while read -r _ _ _ _ state flag; do
  if [[ "$state" != fullscreen ]]; then continue; fi
  if [[ "$flag" == on ]]; then
    xdotool search --class eww-bar windowunmap
  else
    xdotool search --class eww-bar windowmap
  fi
done &
